name: TheZenSpace
favicon: null
layout_spectrum: 0.8785309162922204
typography_spectrum: 0.8992264901753515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10073740617372096
  lightness: 0.28789916704408824
  saturation: 0.6406706301495433
  rhythmicContrast: 0.09817768004722893
purpose: []
